name: Python Discord bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    - name: Run the application
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python3 main.py
